import type { TemplateWorkflow } from '../types/workflow';

export const STARTER_TEMPLATES: TemplateWorkflow[] = [
  {
    id: 'mongodb-ai-ingestion',
    name: '🍃 Webhook to MongoDB Ingestion & AI Ticket Classifier',
    description: 'Receives webhook events, processes payload via AI LLM node, persists structured document into MongoDB collection, and dispatches Slack alert.',
    category: 'Database & AI',
    nodes: [
      {
        id: 'node-1',
        type: 'customNode',
        position: { x: 80, y: 220 },
        data: {
          label: 'Webhook Trigger',
          nodeType: 'webhook_trigger',
          category: 'trigger',
          iconName: 'Webhook',
          color: '#FF5C49',
          parameters: {
            path: '/v1/webhook/support-ticket',
            httpMethod: 'POST',
            authSecret: 'lm_sec_9921',
          },
          status: 'idle',
        },
      },
      {
        id: 'node-2',
        type: 'customNode',
        position: { x: 380, y: 220 },
        data: {
          label: 'AI Prompt / LLM Node',
          nodeType: 'ai_agent',
          category: 'ai',
          iconName: 'Sparkles',
          color: '#06B6D4',
          parameters: {
            model: 'gemini-1.5-pro',
            systemPrompt: 'You are an AI Ticket Dispatcher. Output valid JSON with sentiment, team, and recommended action.',
            userPrompt: 'Customer: {{ $json.customer }}\nIssue: {{ $json.subject }}\nPriority: {{ $json.priority }}',
            temperature: 0.2,
          },
          status: 'idle',
        },
      },
      {
        id: 'node-3',
        type: 'customNode',
        position: { x: 680, y: 120 },
        data: {
          label: 'MongoDB Database',
          nodeType: 'mongodb_node',
          category: 'action',
          iconName: 'Database',
          color: '#10B981',
          parameters: {
            operation: 'insertOne',
            collection: 'incidents',
            queryJson: '{\n  "ticketId": "{{ $json.ticketId }}",\n  "customer": "{{ $json.customer }}",\n  "sentiment": "{{ $node[\"AI Prompt / LLM Node\"].json.sentiment }}",\n  "summary": "{{ $node[\"AI Prompt / LLM Node\"].json.summary }}",\n  "assignedTeam": "{{ $node[\"AI Prompt / LLM Node\"].json.assignedTeam }}",\n  "createdAt": "2026-08-04T13:40:00Z"\n}',
            mongoUri: '{{ $env.MONGODB_URI }}',
          },
          status: 'idle',
        },
      },
      {
        id: 'node-4',
        type: 'customNode',
        position: { x: 680, y: 340 },
        data: {
          label: 'Slack Notifier',
          nodeType: 'slack_node',
          category: 'action',
          iconName: 'MessageSquare',
          color: '#4A154B',
          parameters: {
            channel: '#sre-alerts',
            message: '🍃 *MongoDB Document Saved*: {{ $json.ticketId }}\n*Collection*: incidents\n*AI Summary*: {{ $node["AI Prompt / LLM Node"].json.summary }}',
          },
          status: 'idle',
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'node-1', target: 'node-2', animated: false },
      { id: 'e2-3', source: 'node-2', target: 'node-3', animated: false },
      { id: 'e2-4', source: 'node-2', target: 'node-4', animated: false },
    ],
  },
  {
    id: 'ai-incident-dispatcher',
    name: '🤖 AI Incident Dispatcher & Escalation',
    description: 'Passes problem description to AI LLM Node to evaluate severity, generate team assignment, and post alerts to Slack and Email.',
    category: 'AI & Operations',
    nodes: [
      {
        id: 'node-1',
        type: 'customNode',
        position: { x: 100, y: 220 },
        data: {
          label: 'Webhook Trigger',
          nodeType: 'webhook_trigger',
          category: 'trigger',
          iconName: 'Webhook',
          color: '#FF5C49',
          parameters: {
            path: '/v1/webhook/incoming-incident',
            httpMethod: 'POST',
            authSecret: 'lm_sec_9921',
          },
          status: 'idle',
        },
      },
      {
        id: 'node-2',
        type: 'customNode',
        position: { x: 420, y: 220 },
        data: {
          label: 'AI Prompt / LLM Node',
          nodeType: 'ai_agent',
          category: 'ai',
          iconName: 'Sparkles',
          color: '#06B6D4',
          parameters: {
            model: 'gemini-1.5-pro',
            systemPrompt: 'You are an AI Incident Responder. Classify urgency and assign responsible engineering team in JSON format.',
            userPrompt: 'Incident ID: {{ $json.ticketId }}\nCustomer: {{ $json.customer }}\nIssue: {{ $json.subject }}\nPriority: {{ $json.priority }}',
            temperature: 0.2,
          },
          status: 'idle',
        },
      },
      {
        id: 'node-3',
        type: 'customNode',
        position: { x: 740, y: 120 },
        data: {
          label: 'Slack Notifier',
          nodeType: 'slack_node',
          category: 'action',
          iconName: 'MessageSquare',
          color: '#4A154B',
          parameters: {
            channel: '#sre-alerts',
            message: '🚨 *New Urgent Incident*: {{ $json.ticketId }}\n*Customer*: {{ $json.customer }}\n*AI Summary*: {{ $node["AI Prompt / LLM Node"].json.summary }}\n*Assigned Team*: {{ $node["AI Prompt / LLM Node"].json.assignedTeam }}',
          },
          status: 'idle',
        },
      },
      {
        id: 'node-4',
        type: 'customNode',
        position: { x: 740, y: 340 },
        data: {
          label: 'Email SMTP Sender',
          nodeType: 'email_node',
          category: 'action',
          iconName: 'Mail',
          color: '#6366F1',
          parameters: {
            toEmail: 'oncall-team@company.com',
            subject: 'Escalation Alert: {{ $json.ticketId }}',
            bodyHtml: '<h3>LogicMesh Automated Alert</h3><p>Incident summary: {{ $node["AI Prompt / LLM Node"].json.summary }}</p>',
          },
          status: 'idle',
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'node-1', target: 'node-2', animated: false },
      { id: 'e2-3', source: 'node-2', target: 'node-3', animated: false },
      { id: 'e2-4', source: 'node-2', target: 'node-4', animated: false },
    ],
  },
  {
    id: 'scheduled-api-poller',
    name: '⏱️ Scheduled API Health Poller & Mongo Sync',
    description: 'Runs every 15 minutes to poll server status endpoint via HTTP Request, formats payload using JS Code Node, and routes failures.',
    category: 'Monitoring',
    nodes: [
      {
        id: 'node-1',
        type: 'customNode',
        position: { x: 100, y: 220 },
        data: {
          label: 'Cron Schedule',
          nodeType: 'schedule_trigger',
          category: 'trigger',
          iconName: 'Clock',
          color: '#FF5C49',
          parameters: {
            cronExpression: '*/15 * * * *',
            timezone: 'UTC',
          },
          status: 'idle',
        },
      },
      {
        id: 'node-2',
        type: 'customNode',
        position: { x: 400, y: 220 },
        data: {
          label: 'HTTP Request',
          nodeType: 'http_request',
          category: 'action',
          iconName: 'Globe',
          color: '#6366F1',
          parameters: {
            method: 'GET',
            url: 'https://api.logicmesh.io/health',
            headers: '{\n  "Accept": "application/json"\n}',
            body: '',
          },
          status: 'idle',
        },
      },
      {
        id: 'node-3',
        type: 'customNode',
        position: { x: 700, y: 220 },
        data: {
          label: 'MongoDB Database',
          nodeType: 'mongodb_node',
          category: 'action',
          iconName: 'Database',
          color: '#10B981',
          parameters: {
            operation: 'insertOne',
            collection: 'health_logs',
            queryJson: '{\n  "status": "{{ $json.status }}",\n  "checkedAt": "2026-08-04T13:40:00Z"\n}',
            mongoUri: '{{ $env.MONGODB_URI }}',
          },
          status: 'idle',
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'node-1', target: 'node-2', animated: false },
      { id: 'e2-3', source: 'node-2', target: 'node-3', animated: false },
    ],
  },
];
